description = 'Order Service - Manages customer orders and transactions'

dependencies {

	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	// AWS Step Functions SDK
	implementation platform('software.amazon.awssdk:bom:2.25.0')
	implementation 'software.amazon.awssdk:sfn'

	// Internal modules
	api project(':common-module:data')
	api project(':common-module:utils')
	api project(':common-module:redis-module')
	api project(':common-module:factory-module')
	api project(':common-module:sqs-module')
	api project(':common-module:security-module')
	

}
