spring:
  application:
    name: reservation-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.1
        max-interval: 2000
    aws:
      sns:
        reservation-topic-arn: ${AWS_SNS_RESERVATION_TOPIC_ARN:arn:aws:sns:us-east-1:556607597153:reservation-notifications-dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh

management:
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    redis:
      enabled: false
    sqs:
      enabled: false

restaurant:
  security:
    endpoints:
      - path: /actuator/**
        type: PUBLIC
      - path: /health
        type: PUBLIC
      - path: /api/reservations/guest
        type: PUBLIC
      - path: /api/reservations/availability
        type: PUBLIC
      - path: /api/reservations/confirmation/**
        type: PUBLIC

# Service URLs for Feign clients
profile-service:
  url: http://restaurant-alb-696207792.us-east-1.elb.amazonaws.com

