description = 'Kafka Module - Kafka messaging and event streaming'

dependencies {
	// Spring Cloud AWS SQS
	api 'io.awspring.cloud:spring-cloud-aws-starter-sqs'
	api 'com.fasterxml.jackson.core:jackson-databind'
	
	// Internal modules
	api project(':common-module:data')
	api project(':common-module:utils')
	
	// Configuration processor
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

